### ISSUE TITLE
[BUG] .setPreconditions() results in error

### ISSUE THREAD

**Issue by PAdventures** [thenorthsolution/Reciple#47]
Example Precondition
```ts
export class Precondition {
	public data: CommandPreconditionData = {
                // note that my id is all lowercase and only uses "." as a symbol
		id: 'UNIQUE.PRECONDITION.ID',
		disabled: false,
		slashCommandExecute: (data, precondition) => this._execute(data, precondition),
		contextMenuCommandExecute: (data, precondition) => this._execute(data, precondition),
		messageCommandExecute: (data, precondition) => this._execute(data, precondition),
	};
}
```
Example Command w/ .setPreconditions()
```ts
import Precondition from './path/to/precondition.js'
// cmd
// using Precondition.data.id results in a TS unmatched type error:
// Argument of type '[string]' is not assignable to parameter of type 'RestOrArray<CommandPreconditionResolvable>'

// Here I use the object which doesn't result in a TS error
.setPreconditions(Precondition.data) // ...preconditionIds: RestOrArray<CommandPreconditionResolvable>
```
The .setPrecondition() expects a CommandPreconditionData and yet the error suggests that it expected a string.

Resulting error
```js
[TIME ERROR] Failed to start module '/path/to/project/file.js': CombinedError (2)
[TIME ERROR]   Received one or more errors
[TIME ERROR] 
[TIME ERROR]   1 ExpectedValidationError > s.literal(V)
[TIME ERROR]   |   Expected values to be equals
[TIME ERROR]   | 
[TIME ERROR]   |   Expected:
[TIME ERROR]   |   | undefined
[TIME ERROR]   | 
[TIME ERROR]   |   Received:
[TIME ERROR]   |   | [ [Object] ]
[TIME ERROR] 
[TIME ERROR]   2 CombinedPropertyError (1)
[TIME ERROR]   |   Received one or more errors
[TIME ERROR]   | 
[TIME ERROR]   |   input[0]
[TIME ERROR]   |   | ValidationError > s.string
[TIME ERROR]   |   |   Expected a string primitive
[TIME ERROR]   |   | 
[TIME ERROR]   |   |   Received:
[TIME ERROR]   |   |   | [Object]
[TIME ERROR] 
[TIME ERROR]     at _UnionValidator.handle (/path/to/project/node_modules/@sapphire/shapeshift/dist/cjs/index.cjs:1125:23)
[TIME ERROR]     at _UnionValidator.parse (/path/to/project/node_modules/@sapphire/shapeshift/dist/cjs/index.cjs:216:88)
[TIME ERROR]     at BaseCommandValidators.isValidPreconditions (/path/to/project/node_modules/@reciple/core/dist/classes/validators/BaseCommandValidators.js:36:109)
[TIME ERROR]     at SlashCommandBuilder.setPreconditions (/path/to/project/node_modules/@reciple/core/dist/classes/builders/BaseCommandBuilder.js:52:55)
[TIME ERROR]     at FILE.onStart (file:///path/to/project/modules/path/to/file.js:26:18)
[TIME ERROR]     at RecipleModule.start (/path/to/project/node_modules/@reciple/core/dist/classes/structures/RecipleModule.js:35:54)
[TIME ERROR]     at ModuleManager.startModules (/path/to/project/node_modules/@reciple/core/dist/classes/managers/ModuleManager.js:30:25)
[TIME ERROR]     at async file:///path/to/project/node_modules/reciple/dist/bin.mjs:70:24
```
> [!NOTE]
> This may be an issue with my code as I'm not familiar with Reciple yet! Or this is a bug that I can't solve

**Comment by NotGhex** [comment]
Fixed at a94e34a7ba0a02db0d3ff40a9e72e634724b1d04
